import PDFDocument from 'pdfkit';

export const generatePDFReport = ({ patient, plans, progress }) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const buffers = [];

    doc.on('data', (chunk) => buffers.push(chunk));
    doc.on('end',  () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    // Header
    doc.fontSize(24).font('Helvetica-Bold').text('RehabTracer', { align: 'center' });
    doc.fontSize(14).font('Helvetica').text('Patient Rehabilitation Report', { align: 'center' });
    doc.moveDown();
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown();

    // Patient Info
    doc.fontSize(16).font('Helvetica-Bold').text('Patient Information');
    doc.moveDown(0.5);
    doc.fontSize(12).font('Helvetica');
    doc.text(`Name:              ${patient.user.name}`);
    doc.text(`Email:             ${patient.user.email}`);
    doc.text(`Age:               ${patient.age}`);
    doc.text(`Gender:            ${patient.gender}`);
    doc.text(`Medical Condition: ${patient.medicalCondition}`);
    doc.text(`Report Generated:  ${new Date().toLocaleDateString()}`);
    doc.moveDown();

    // Active Plan
    if (plans) {
      doc.fontSize(16).font('Helvetica-Bold').text('Active Rehabilitation Plan');
      doc.moveDown(0.5);
      doc.fontSize(12).font('Helvetica');
      doc.text(`Plan:        ${plans.title}`);
      doc.text(`Status:      ${plans.status}`);
      doc.text(`Start Date:  ${new Date(plans.startDate).toLocaleDateString()}`);
      doc.text(`Recovery:    ${plans.currentRecoveryPct}%`);
      doc.moveDown();

      if (plans.exercises?.length > 0) {
        doc.fontSize(14).font('Helvetica-Bold').text('Exercises');
        plans.exercises.forEach((ex, i) => {
          doc.fontSize(12).font('Helvetica').text(
            `${i + 1}. ${ex.name} — ${ex.sets || '-'} sets × ${ex.reps || '-'} reps — ${ex.isCompleted ? '✓ Done' : 'Pending'}`
          );
        });
        doc.moveDown();
      }
    }

    // Progress Summary
    if (progress?.length > 0) {
      doc.fontSize(16).font('Helvetica-Bold').text('Recent Progress (Last 30 Days)');
      doc.moveDown(0.5);
      doc.fontSize(11).font('Helvetica');

      const avgPain    = (progress.reduce((s, p) => s + p.painLevel, 0) / progress.length).toFixed(1);
      const avgRecovery= (progress.reduce((s, p) => s + p.recoveryPct, 0) / progress.length).toFixed(1);

      doc.text(`Total Logs:        ${progress.length}`);
      doc.text(`Avg Pain Level:    ${avgPain} / 10`);
      doc.text(`Avg Recovery:      ${avgRecovery}%`);
      doc.moveDown(0.5);

      progress.slice(0, 10).forEach((p) => {
        doc.text(
          `${new Date(p.date).toLocaleDateString()} — Pain: ${p.painLevel}/10 — Recovery: ${p.recoveryPct}% — Mood: ${p.mood || '-'}`
        );
      });
    }

    // Footer
    doc.moveDown(2);
    doc.fontSize(10).fillColor('grey').text(
      'This report is auto-generated by RehabTracer. For clinical decisions, consult your physician.',
      { align: 'center' }
    );

    doc.end();
  });
};